# Generated by Django 2.0 on 2018-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('user_id', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('other_names', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=4)),
                ('tel_number', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
