# Generated by Django 2.0 on 2018-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_and_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='userbase',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
